# Токен для бота в телеграме
API_TOKEN: 'YOUR TOKEN'

# Период, на который будет доступно бронирование парковочных мест
RESERVATION_PERIOD_DAYS: 4

# Имена для парковочных мест.
# Можно придумать осмысленные значения.
# Можно указать код/номер.
PARKING_SPOTS: ["333", "464", "501"]

# Имя базы данных SQLite, где будет храниться вся информация
DB_NAME: "parking_spots.db"

# Пользователи, которые будут добавляться в базу при запуске бота
USERS:
  - username: "krivosoft"
    first_name: "Vladimir"
    last_name: "Pn"
    role: "AUDITOR"
    telegram_id: 1543421535
    # role может принимать значения: ADMINISTRATOR, AUDITOR или CLIENT
    # Если username нет, то вставить пустую строку ""

# Время в 24-часовом формате
TODAY_DEADLINE_CLOCK_FOR_CLIENTS: 7 # <- Клиенты могут бронировать места на сегодняшний день, до 7 часов.
# После - на следующий день
TODAY_DEADLINE_CLOCK_FOR_AUDITORS: 9 # <- Аудиторы получают отчёт за сегодняшний день до 9 часов.
# После - за следующий день.
